docker:
  db: {}
domains: []
git:
  main_deployment_remote_name: github
  publication_strategy: main_push
global:
  name: js_pseudocode
  type: app
  version: 0.1.37
wex:
  migration: 1
  version: 6.0.133
